### ISSUE TITLE
作業場所の住所を元にgoogle mapを表示する

### ISSUE THREAD

**Issue by TomoyaIkarashi0023** [lx-abe/shigotoba#48]
## 作業内容
- 作業場所詳細画面にgoogle mapを表示し住所の箇所にピンを立てる
- どのように実装すれば良いか調べる
- ボリュームが多いならISSUEを小分けしてみる

**Comment by TomoyaIkarashi0023** [comment]
無料分までなら行けると思ったが、API KEY発行するためにクレジットの登録がいるので断念、、

**Comment by ledsun** [comment]
[投稿された住所をマップに反映させるRailsアプリを作る - Qiita](https://qiita.com/mi-miya/items/1f1c6b68d83395804c1b) OpenStreetMap と leaflet を使う方法もあるみたいです。
参考にどうぞ
